const team = [ {
    name: "Sviatoslav",
    surname: "Larionov",
    age: 19,
    city: "Biella",
    hobby: "Skate",
    favoriteFood: "Rice",
    favoriteVideoGame: "CS:GO",
    favoriteFilm: "Batman",
    favoriteBook: "Demian",
    petName: "",
    },
    {
    name: "Vincenzo",
    surname: "Federico",
    age: 28,
    city: "Palermo",
    hobby: "calcio",
    favoriteFood: "pasta",
    favoriteVideoGame: "Diablo",
    favoriteFilm: "Limitless",
    favoriteBook: "HarryPotter",
    petName: "Argo",
} ];